export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const CLEAR_DATA = "CLEAR_DATA";

export const FETCH_MARKERS = "FETCH_MARKERS";
export const FETCH_SINGLE_MARKER = "FETCH_SINGLE_MARKER";
export const DELETE_MARKER = "DELETE_MARKER";
