export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const CLEAR_DATA = "CLEAR_DATA";
export const FETCH_MARKERS = "FETCH_MARKERS";
export const FETCH_USER_LOCATION = "FETCH_USER_LOCATION";
export const FETCH_USER_MARKERS = "FETCH_USER_MARKERS";
export const UPDATE_USER_LOCATION = "UPDATE_USER_LOCATION";
